name: Minha Primeira Linha de Montagem
on:
  push:
    branches: [ main ]

jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    # env:
      # Esta linha causa o aviso de "forced to run on Node 24", 
      # mas garante que você use a versão mais nova. Comentei nesta última versão
      # FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  
    
    steps:
      - name: 1. Pegar o chassi do carro (código-fonte)
        uses: actions/checkout@v4

      - name: Instalar Node.js versão 24 
        uses: actions/setup-node@v4 
        with: 
          node-version: '24' # AQUI: Removi o hífen que estava antes de node-version

      - name: 1.5. Fabricar o produto
        run: echo "Este é o nosso produto final!" > produto.txt
    
      - name: 2. Estação de Build (Montagem)
        run: echo "Construindo o projeto... Verificando se todas as peças se encaixam!"

      - name: 3. Estação de Teste (Controle de Qualidade)
        run: echo "Rodando os testes automatizados... Verificando se a porta abre e fecha!"

      - name: 4. Empacotar o produto final (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: pacote-do-produto
          path: produto.txt
